#head
spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password:
    database: 0 #redis默认有16个库，用select命令来切换
    timeout: 6000
    #jedis:
    lettuce:
      pool:
        min-idle: 0 #最小空闲连接数
        max-idle: 8 #最大空闲连接数
        max-active: 8 #最大活跃链接数
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#tail
