#head
server:
  port: 8080
  connection-timeout: 10000
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    #password:
    database: 0
    timeout: 6000
    ssl: false
    #cluster:
    #sentinel:
#tail
