#head
spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 6000
    jedis:
      pool:
        max-active: 8 #最大活跃链接数
        max-idle: 8 #最大空闲连接数
        min-idle: 0 #最小空闲连接数
#tail
