#head
spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 6000
    pool:
      min-idle: 30
      max-idle: 100
      max-active: 100
      max-wait: 500
#tail
